# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/47113a2a-8456-4f99-9418-45fa266b0d67";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7f777865-8777-470a-82b2-dbfc6ff19c37".device = "/dev/disk/by-uuid/7f777865-8777-470a-82b2-dbfc6ff19c37";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4CB7-364E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/hdd/DATA" =
    { device = "/dev/disk/by-label/DATA";
      fsType = "ntfs";
      options = [
        "users"
        "nofail"
        "uid=alan"
        "gid=users"
      ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f853e7ce-22a7-4f59-881c-ea0cf3fccfd6"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-6ae97991d02d.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-c1d389d66ac6.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.ztppivq3mg.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
